apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: static-auth2
  namespace: default
spec:
  method: kubernetes
  mount: demo-auth-mount
  kubernetes:
    role: issuer
    serviceAccount: issuer
    audiences:
      - vault
